server:
  port: 8282

spring:
    config:
        activate:
            on-profile: default
            
value: 10
  
---

server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: prod
            
value: 20
   
---

server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: dev
            
value: 30
