server:
  port: 8282

spring:
    config:
        activate:
            on-profile: prod
            
my:
   hostName: Ana
   myclass: 4
  
---

server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: prod
            
my:
   hostName: Ela
   myclass: 8
   
---

server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: dev
            
my:
   hostName: Elena
   myclass: 12
