server:
  port: 8282

spring:
    config:
        activate:
            on-profile: prod
  
---
server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: prod

---
server:
  port: 8282
  
spring:
    config:
        activate:
            on-profile: dev
